"""
AgentCore Strands Agent Generation Handlers

Implementation of handlers for generating Strands agent code with various
configurations and integrations.
"""

from typing import Dict


async def handle_generate_strands_agent(args: Dict) -> Dict:
    """Generate standalone Strands Agent Python code"""
    
    agent_name = args["agent_name"]
    system_prompt = args["system_prompt"]
    model_id = args.get("model_id", "us.anthropic.claude-sonnet-4-5-20250929-v1:0")
    temperature = args.get("temperature", 0.3)
    tools = args.get("tools", [])
    custom_tools = args.get("custom_tools", [])
    
    # Build imports
    imports = ["from strands import Agent, tool"]
    imports.append("from strands.models import BedrockModel")
    
    if "retrieve" in tools:
        imports.append("from strands_tools import retrieve")
    if "current_time" in tools:
        imports.append("from strands_tools import current_time")
    
    if custom_tools:
        imports.append("from datetime import datetime")
    
    # Build tool list
    tool_list = []
    if "retrieve" in tools:
        tool_list.append("retrieve")
    if "current_time" in tools:
        tool_list.append("current_time")
    
    # Generate code
    code = f'''"""
Standalone Strands Agent: {agent_name}
Generated by AgentCore MCP Server
"""

{chr(10).join(imports)}

# Model configuration
MODEL_ID = "{model_id}"
bedrock_model = BedrockModel(model_id=MODEL_ID, temperature={temperature})

# System prompt
system_prompt = """{system_prompt}"""
'''
    
    # Add custom tool definitions
    if custom_tools:
        code += "\n# Custom tool definitions\n"
        for tool_def in custom_tools:
            tool_name = tool_def.get("name", "custom_tool")
            tool_desc = tool_def.get("description", "Custom tool")
            tool_code = tool_def.get("code", 'return "Not implemented"')
            
            # Automatically add @tool decorator if not present
            if not tool_code.strip().startswith("@tool"):
                code += f'''@tool
{tool_code}

'''
            else:
                code += f'''{tool_code}

'''
            tool_list.append(tool_name)
    
    code += f'''
# Create agent
agent = Agent(
    model=bedrock_model,
    tools=[{", ".join(tool_list)}],
    system_prompt=system_prompt
)

def run_agent(user_input: str):
    """Run the agent with user input"""
    response = agent(user_input)
    return response.message["content"][0]["text"]

if __name__ == "__main__":
    # Example usage
    user_query = "Hello, how can you help me?"
    result = run_agent(user_query)
    print(result)
'''
    
    return {
        "status": "generated",
        "agent_name": agent_name,
        "filename": f"{agent_name}.py",
        "code": code,
        "instructions": f"Save this code to {agent_name}.py and run with: python {agent_name}.py"
    }


async def handle_generate_agentcore_runtime_agent(args: Dict) -> Dict:
    """Generate AgentCore Runtime-ready Strands Agent with BedrockAgentCoreApp entrypoint"""
    
    agent_name = args["agent_name"]
    system_prompt = args["system_prompt"]
    model_id = args.get("model_id", "us.anthropic.claude-sonnet-4-5-20250929-v1:0")
    temperature = args.get("temperature", 0.3)
    include_memory = args.get("include_memory", True)
    memory_namespaces = args.get("memory_namespaces", ["semantic", "preferences", "summary"])
    include_kb = args.get("include_kb", False)
    include_gateway = args.get("include_gateway", False)
    additional_tools = args.get("additional_tools", [])
    region = args.get("region")
    if not region:
        raise ValueError("region parameter is required")
    
    # Build imports
    imports = [
        "import os",
        "import json",
        "from bedrock_agentcore.runtime import BedrockAgentCoreApp",
        "from strands import Agent, tool",
        "from strands.models import BedrockModel"
    ]
    
    tool_list = []
    
    if include_kb:
        imports.append("from strands_tools import retrieve")
        tool_list.append("retrieve")
    
    if "current_time" in additional_tools:
        imports.append("from strands_tools import current_time")
        tool_list.append("current_time")
    
    if include_gateway:
        imports.append("from strands.tools.mcp import MCPClient")
        imports.append("from mcp.client.streamable_http import streamablehttp_client")
        imports.append("import requests")
    
    if include_memory:
        imports.append("from bedrock_agentcore.memory.integrations.strands.config import AgentCoreMemoryConfig, RetrievalConfig")
        imports.append("from bedrock_agentcore.memory.integrations.strands.session_manager import AgentCoreMemorySessionManager")
    
    # Generate code
    code = f'''"""
AgentCore Runtime Agent: {agent_name}
Generated by AgentCore MCP Server

This agent is ready to deploy to AgentCore Runtime with:
1. BedrockAgentCoreApp entrypoint
2. Memory integration (optional)
3. Gateway tools (optional)
4. Knowledge Base access (optional)
"""

{chr(10).join(imports)}

# Constants
MODEL_ID = "{model_id}"
REGION = "{region}"
SESSION_ID = "default-session"
ACTOR_ID = "default-actor"

# Initialize app only (don't initialize model at module level)
app = BedrockAgentCoreApp()

# Environment variables - loaded at runtime, not at module import
# These will be accessed inside the invoke function
'''
    
    if include_kb:
        code += '''kb_id = os.environ.get("KNOWLEDGE_BASE_ID", "NOT AVAILABLE")

# Configure retrieve tool with Knowledge Base
if kb_id != "NOT AVAILABLE":
    from strands_tools import retrieve
    retrieve = retrieve.with_config(
        knowledgeBaseId=kb_id,
        region=REGION
    )
    print(f"✓ Knowledge Base configured: {kb_id}")
else:
    print("⚠️  KNOWLEDGE_BASE_ID not set - retrieve tool will not work")
'''
    
    # Remove module-level environment variable loading
    # Memory ID will be loaded inside invoke function
    
    if include_gateway:
        code += '''
# ============================================================================
# GATEWAY HELPER FUNCTIONS
# ============================================================================

def get_cognito_token_with_scope(client_id, client_secret, discovery_url, scope):
    """Get Cognito bearer token with a specific OAuth scope"""
    # Extract token endpoint from discovery URL
    discovery_response = requests.get(discovery_url)
    token_endpoint = discovery_response.json()['token_endpoint']
    
    # Get token using client credentials flow
    response = requests.post(
        token_endpoint,
        data={{
            'grant_type': 'client_credentials',
            'client_id': client_id,
            'client_secret': client_secret,
            'scope': scope
        }},
        headers={{'Content-Type': 'application/x-www-form-urlencoded'}}
    )
    
    response.raise_for_status()
    return response.json()["access_token"]

def create_mcp_client():
    """Create MCP client for gateway access"""
    # Get environment variables
    gateway_url = os.environ.get("GATEWAY_URL")
    cognito_client_id = os.environ.get("COGNITO_CLIENT_ID")
    cognito_client_secret = os.environ.get("COGNITO_CLIENT_SECRET")
    cognito_discovery_url = os.environ.get("COGNITO_DISCOVERY_URL")
    oauth_scopes = os.environ.get("OAUTH_SCOPES", "returns-gateway/read returns-gateway/write returns-gateway/invoke")
    
    if not all([gateway_url, cognito_client_id, cognito_client_secret, cognito_discovery_url]):
        return None
    
    try:
        token = get_cognito_token_with_scope(
            cognito_client_id,
            cognito_client_secret,
            cognito_discovery_url,
            oauth_scopes
        )
        return MCPClient(
            lambda: streamablehttp_client(
                gateway_url,
                headers={{"Authorization": f"Bearer {{token}}"}},
            )
        )
    except Exception as e:
        print(f"Warning: Failed to create MCP client: {{e}}")
        return None
'''
    
    # System prompt
    kb_note = f'\\n- Knowledge Base (retrieve tool with knowledgeBaseId="{{kb_id}}") for domain knowledge' if include_kb else ""
    gateway_note = "\\n- Gateway tools for external operations" if include_gateway else ""
    memory_note = "\\n- Customer conversation history and preferences through memory" if include_memory else ""
    
    code += f'''
system_prompt = """{system_prompt}{kb_note}{gateway_note}{memory_note}"""

@app.entrypoint
def invoke(payload, context=None):
    """AgentCore Runtime entrypoint"""
    try:
        # Initialize model inside the function (not at module level)
        bedrock_model = BedrockModel(model_id=MODEL_ID, temperature={temperature})
        
        # Get environment variables
'''
    
    if include_memory:
        # Build memory retrieval config
        retrieval_configs = []
        for ns in memory_namespaces:
            if ns == "summary":
                retrieval_configs.append(f'            f"app/{{actor_id}}/{{session_id}}/summary": RetrievalConfig(top_k=2),')
            else:
                retrieval_configs.append(f'            f"app/{{actor_id}}/{ns}": RetrievalConfig(top_k=3),')
        
        code += f'''        memory_id = os.environ.get("MEMORY_ID")
        if not memory_id:
            return "Error: MEMORY_ID environment variable is required"
        
        session_id = context.session_id if context else SESSION_ID
        actor_id = payload.get("actor_id", ACTOR_ID)
        
        # Configure memory with retrieval settings
        agentcore_memory_config = AgentCoreMemoryConfig(
            memory_id=memory_id,
            session_id=session_id,
            actor_id=actor_id,
            retrieval_config={{
{chr(10).join(retrieval_configs)}
            }}
        )
        
        session_manager = AgentCoreMemorySessionManager(
            agentcore_memory_config=agentcore_memory_config,
            region_name=REGION
        )
        
        # Custom tools list
        custom_tools = [{", ".join(tool_list)}]
        
'''
    else:
        code += '''        session_id = context.session_id if context else SESSION_ID
        actor_id = payload.get("actor_id", ACTOR_ID)
        
        # Custom tools list
        custom_tools = [''' + ", ".join(tool_list) + ''']
        
'''
    
    if include_gateway:
        code += '''        # Try to create MCP client for gateway tools
        mcp_client = create_mcp_client()
        
        if mcp_client:
            try:
                # Keep MCP client active during agent execution
                with mcp_client:
                    # Get gateway tools from MCP client
                    gateway_tools = list(mcp_client.list_tools_sync())
                    
                    # Create agent with all tools
                    agent = Agent(
                        model=bedrock_model,
                        tools=custom_tools + gateway_tools,
                        system_prompt=system_prompt'''
        
        if include_memory:
            code += ''',
                        session_manager=session_manager'''
        
        code += '''
                    )
                    
                    user_input = payload.get("prompt", "")
                    response = agent(user_input)
                    return response.message["content"][0]["text"]
            except Exception as e:
                print(f"Warning: Failed to use gateway tools: {{e}}")
                # Fall back to agent without gateway tools
        
        # Create agent without gateway tools (fallback)
        agent = Agent(
            model=bedrock_model,
            tools=custom_tools,
            system_prompt=system_prompt'''
        
        if include_memory:
            code += ''',
            session_manager=session_manager'''
        
        code += '''
        )
        
        user_input = payload.get("prompt", "")
        response = agent(user_input)
        return response.message["content"][0]["text"]
'''
    else:
        code += '''        # Create agent
        agent = Agent(
            model=bedrock_model,
            tools=custom_tools,
            system_prompt=system_prompt'''
        
        if include_memory:
            code += ''',
            session_manager=session_manager'''
        
        code += '''
        )
        
        user_input = payload.get("prompt", "")
        response = agent(user_input)
        return response.message["content"][0]["text"]
'''
    
    code += '''    
    except Exception as e:
        error_msg = f"Agent invocation failed: {{str(e)}}"
        print(error_msg)
        import traceback
        traceback.print_exc()
        return error_msg

if __name__ == "__main__":
    app.run()
'''
    
    # Generate deployment instructions
    env_vars = []
    if include_memory:
        env_vars.append("MEMORY_ID")
    if include_kb:
        env_vars.append("KNOWLEDGE_BASE_ID")
    if include_gateway:
        env_vars.extend(["GATEWAY_URL", "COGNITO_CLIENT_ID", "COGNITO_CLIENT_SECRET", "COGNITO_DISCOVERY_URL"])
    
    instructions = f"""1. Save this code to {agent_name}.py
2. Configure Runtime deployment:
   - Use MCP tool: agentcore_runtime_configure
   - Set entrypoint: {agent_name}.py
   - Set agent_name: {agent_name}
3. Launch to Runtime:
   - Use MCP tool: agentcore_runtime_launch
   - Set environment variables: {", ".join(env_vars)}
4. Test deployment:
   - Use MCP tool: agentcore_runtime_status
   - Use MCP tool: agentcore_runtime_invoke"""
    
    return {
        "status": "generated",
        "agent_name": agent_name,
        "filename": f"{agent_name}.py",
        "code": code,
        "instructions": instructions.strip(),
        "required_env_vars": env_vars
    }


# ============================================================================
# MAIN
